name: Windows

on:
  push:
    branches:
      - master
    pull_request:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "20"
          arch: "x64"

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: 6.9.3
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          modules: qthttpserver qtwebsockets

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v2

      - name: Install NSIS
        run: choco install nsis -y

      - name: Configure
        shell: bash
        run: |
          cmake -G Ninja -B check -S . -DCMAKE_PREFIX_PATH="%Qt6_DIR%" -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
          cmake -B build -S . -A x64 -DCMAKE_PREFIX_PATH="%Qt6_DIR%" -DGIT_VERSION=${{ github.ref_name }}-${GITHUB_SHA::8}

      - name: Formet check
        run: '& "${{ env.LLVM_PATH }}/bin/clang-format" -i ./src/*.cxx -i ./src/*.hxx --dry-run --Werror'

      - name: Static check
        run: '& "${{ env.LLVM_PATH }}/bin/clang-tidy" -p check -header-filter="src/.*" src/*.cxx src/*.hxx -warnings-as-errors="*"'

      - name: Build
        run: cmake --build build --config Release

      - name: Pack
        working-directory: build
        run: cpack -C Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer
          path: |
            build/PicMover*.exe

  release:
    runs-on: windows-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    permissions:
      contents: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: installer

      - name: Create release
        uses: comnoco/create-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          prerelease: ${{ contains(github.ref_name, '-') }}
          draft: false

      - name: Upload release assets
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.exe"
          tags: true
          draft: false